version: "3"

services:

  nacos:
    image: nacos/nacos-server:v2.1.1
    restart: always
    container_name: nacos
    env_file:
      - .env
    volumes:
      - ./logs/:/home/nacos/logs
    ports:
      - "8848:8848"
    depends_on:
      mysql:
        condition: service_healthy
