version: "3"

networks:
  broker:
    external: true

services:
  mysql:
    container_name: mysql
    restart: always
    build:
      context: .
      dockerfile: ./build/mysql/Dockerfile
    env_file:
      - .env
    volumes:
      - ./mysql:/var/lib/mysql
    networks:
      - broker
    ports:
      - "3306:3306"
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      interval: 5s
      timeout: 10s
      retries: 10

  nacos:
    image: nacos/nacos-server:v2.1.1
    restart: always
    container_name: nacos
    env_file:
      - .env
    volumes:
      - ./logs/:/home/nacos/logs
    ports:
      - "8848:8848"
    depends_on:
      mysql:
        condition: service_healthy
