version: "3"

networks:
  default:
    external:
      name: broker

services:

  nacos:
    image: nacos/nacos-server:v2.1.1
    restart: always
    container_name: nacos
    env_file:
      - .env
    volumes:
      - ./logs/:/home/nacos/logs
    networks:
      - broker
    ports:
      - "8848:8848"
