---
- hosts: all
  become: true
  vars_files:
    - vars/main.yml

  roles:
    - role: geerlingguy.docker

  tasks:
    - name: Install Packages
      ansible.builtin.yum:
        name:
          - python-docker
          - git
          - vim
        state: present
