---
- hosts: all
  become: true
  vars_files:
    - vars/main.yml

  roles:
    - role: geerlingguy.docker

  tasks:
    - name: Create broker network
      community.docker.docker_network:
        name: broker
      register: result
      until: result is succeeded
