---
- hosts: all
  become: true
  vars_files:
    - vars/main.yml

  roles:
    - role: geerlingguy.docker

  tasks:
    - name: Install Packages
      ansible.builtin.yum:
        name: python3-docker
        install_recommends: false

    - name: Create broker network
      community.docker.docker_network:
        name: broker
      register: result
      until: result is succeeded
